name: clean_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.6.4
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  http: ^1.1.0
  # Local cache
  shared_preferences: ^2.2.2
  meta: ^1.9.1
  matcher: ^0.12.16
  mocktail: ^1.0.1
  internet_connection_checker_plus: ^2.1.0
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
